### ISSUE TITLE
Delete a repo

### ISSUE THREAD

**Issue by proustibat** [lolcommits/lolcommits-dot-com#3]
Hi! 
I created a repo on http://lolcommits-dot-com.herokuapp.com/ but I would like to delete it, is it possible and how ?
Is it also possible to have all pic from all projects in only one repo ?

Thks

**Comment by matthutchinson** [comment]
We currently don't have a delete button for repo's - if you like, I can jump into the console and delete the repo for you.  Just email me (matt@hiddenloop.com) the Repo External ID, and your lolcommits-dot-com user API key (so I can verify it is you).

Also -- since lolcommits (the gem) is per repo based, and the dot-com lolcommits plugin posts images on a per repo basis, then the images are always attached to a single repo.  Pull-requests on both projects are welcome if you'd like to change any of this yourself.

**Comment by matthutchinson** [comment]
Thanks for the info in your email - repo deleted now 👍

**Comment by matthutchinson** [comment]
FYI, with this [latest PR](https://github.com/lolcommits/lolcommits-dot-com/pull/4) now deployed and live, you can now do this in the app itself.
